### ISSUE TITLE
PM issues (Chrome, Firefox) 

### ISSUE THREAD

**Issue by AlexBryson** [Monchoman45/Torus#16]
Torus 2.4.0, tested in Chrome and Firefox - both not working

Seemingly 2 issues:
1. PMs don't pop up, someone said "RansomTime PM" in chat and when I clicked to PM with them I saw a message history.
2. PMs don't show when you send them:
   Reproduce steps:
   a) http://c.wikia.com/wiki/Special:Torus
   b) start a PM with URL
   c) attempt to send a message

Expected: The message is seen
Actual: The message isn't seen, but refreshing torus and starting an new PM shows this message, implying that it was sent.

**Comment by Monchoman45** [comment]
When you opened a PM, it would try to read pings for the PM instead of the parent. Turned out to be the same thing for both, the error opening the room probably left it in a bad state. Works as intended now.
