### ISSUE TITLE
URLs that ping you don't work as expected

### ISSUE THREAD

**Issue by AlexBryson** [Monchoman45/Torus#23]
When you get pinged, the </span> for the ping appears in the href:

Steps to reproduce
1. Turn pings on
2. Link to a something with a ping phrase in the name
3. Click link
4. Cry
![torus](https://cloud.githubusercontent.com/assets/8709821/8759051/9d0a3f58-2ce4-11e5-93b1-f2b55bf0546f.png)

**Comment by Monchoman45** [comment]
Fixed, but I can't update publicly right now because I'm not allowed to edit MediaWiki pages. This'll be live whenever I can do that again.
