### ISSUE TITLE
Joining wiki chat rooms with more than one word

### ISSUE THREAD

**Issue by TheOtherUnknown** [Monchoman45/Torus#26]
For some reason, attempting to join the chat room of a wiki with more than one word in the URL (i.e Rider_ranger47 or fusion-of-worlds) returns the error "no chat" when there in fact is.

**Comment by Monchoman45** [comment]
This is probably due to caching; if you wait a while, it should be fine.

**Comment by TheOtherUnknown** [comment]
Yeah,  that fixed it.
